# Reference for exteranl_links and bridge containers
# https://blog.virtualzone.de/2016/09/docker-compose-link-containers-outside-compose-file-using-external_links.html

version: '2'
services:
  base:
    build: .
    image: promgen
    network_mode: bridge
    command: sh -c "promgen migrate && promgen register docker-demo localhost 9090"
    external_links:
      - mysql
      - rabbitmq
    environment:
      CELERY_BROKER_URL: amqp://guest@rabbitmq:5672//
      DATABASE_URL: mysql://promgen:promgen@mysql:3306/pypromgen
      SECRET_KEY: asdf

  web:
    extends: base
    command: promgen runserver 0.0.0.0:8000
    ports:
      - "8080:8000"
    links:
      - prometheus
      - alertmanager
      - blackbox
    environment:
      DEBUG: 1

  worker:
    extends: base
    command: worker -l info --queues localhost,celery
    links:
      - prometheus
    volumes:
      - ./docker:/etc/prometheus
    environment:
      DEBUG: 1

  ecr-exporter-test:
    image: ecr-exporter:latest
    command: python ecr_exporter.py
    network_mode: bridge
    ports:
      - "9105:9105"
    environment:
      AWS_ACCESS_KEY_ID: ***REMOVED***
      AWS_SECRET_ACCESS_KEY: ***REMOVED***
      AWS_DEFAULT_REGION: ***REMOVED***

  prometheus:
    image: prom/prometheus
    network_mode: bridge
    links:
      - alertmanager
      - blackbox
      - ecr-exporter-test
    ports:
      - "9090:9090"
    volumes:
      - ./docker:/etc/prometheus

  blackbox:
    image: prom/blackbox-exporter
    network_mode: bridge
    volumes:
      - ./docker:/etc/prometheus

  alertmanager:
    image: prom/alertmanager
    command: -config.file=/etc/prometheus/alertmanager.yml
    network_mode: bridge
    ports:
      - "9093:9093"
    volumes:
      - ./docker:/etc/prometheus
